# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'puma', '~> 4.3.12'
gem 'rake', '~> 13.0.1'

gem 'config', '~> 2.2.1'
gem 'i18n', '~> 1.8.2'

gem 'bunny', '~> 2.15.0'

gem 'dry-initializer', '~> 3.0.3'
gem 'dry-validation', '~> 1.5.0'

gem 'activesupport', '~> 6.0.0', require: false
gem 'fast_jsonapi', '~> 1.5'

gem 'faraday'
gem 'faraday_middleware'

gem 'rack-ougai', '~> 0.2.1'

gem 'prometheus-client', '~> 2.1.0'

group :development do
  gem 'amazing_print'
end

group :test do
  gem 'factory_bot', '~> 5.2.0'
  gem 'rspec', '~> 3.9.0'
end
