---
- hosts: app
  gather_facts: no
  vars:
    image: ads
  tasks:
    - name: setup facts
      set_fact:
        timestamp: '{{ lookup("pipe", "date -u +%Y%m%d%H%M%S") }}'
    - name: build docker image
      delegate_to: 127.0.0.1
      docker_image:
        build:
          path: ../
          pull: no
        name: '{{ image }}'
        source: build
        force_source: yes
    - name: save image to file
      delegate_to: 127.0.0.1
      docker_image:
        name: '{{ image }}'
        tag: latest
        archive_path: '{{ image }}.tar'
        source: local
    - name: compress image
      delegate_to: 127.0.0.1
      archive:
        path: '{{ image }}.tar'
        dest: '{{ image }}.tar.gz'
        remove: yes
    - name: upload image
      copy:
        src: '{{ image }}.tar.gz'
        dest: '/tmp/{{ timestamp }}-{{ image }}.tar.gz'
    - name: extract image
      shell: 'gunzip {{ timestamp }}-{{ image }}.tar.gz'
      args:
        chdir: /tmp
    - name: stop a container
      become: yes
      docker_container:
        name: '{{ image }}'
        state: absent
    - name: remove old image
      become: yes
      docker_image:
        state: absent
        name: '{{ image }}'
        tag: latest
    - name: load image
      become: yes
      docker_image:
        name: '{{ image }}'
        load_path: '/tmp/{{ timestamp }}-{{ image }}.tar'
        source: load
        force_tag: yes
    - name: remove image file
      file:
        path: '/tmp/{{ timestamp }}-{{ image }}.tar'
        state: absent
    - name: run database migrations
      become: yes
      run_once: yes
      docker_container:
        name: ads-migrations
        image: '{{ image }}'
        network_mode: host
        detach: no
        cleanup: yes
        command: bin/rake db:migrate
        env_file: '/home/{{ ansible_user }}/.env'
    - name: start docker container
      become: yes
      docker_container:
        name: '{{ image }}'
        image: '{{ image }}'
        network_mode: host
        restart_policy: on-failure
        restart_retries: 0
        tty: yes
        env_file: '/home/{{ ansible_user }}/.env'
        state: started