global:
  scrape_interval: 30s
scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
  - job_name: 'services'
    static_configs:
      - targets: ['host.docker.internal:3000', 'host.docker.internal:3020', 'host.docker.internal:3040']